config/routes.rb
Forum::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register" }
  resources :posts do

    resources :comments
  end
  get 'posts/:id/user' => 'posts#userIndex' ,as: 'user_index'
  root :to => 'posts#index'
  get 'admin' => 'admins#index', as: 'admin_index'
  get 'admin/users' => 'admins#listUsers', as: 'admin_list_users'
  get 'admin/logs' => 'admins#listAllLogs', as: 'admin_list_logs'
  get 'admin/logs/:id' => 'admins#listLogs', as: 'admin_user_logs'
  get '/search' => 'posts#search', as: "search"
  get 'tags/:tag', to: 'posts#tags', as: :tag
  get 'tags' => 'posts#tags_list', as: 'tags'

  

end

app/models/activitylog.rb
class Activitylog < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy	
	validates :title, presence: true, length: { minimum: 5 }
	acts_as_taggable
	acts_as_taggable_on :tags


	def self.search(search)
	  if search
	    find(:all, :conditions => ['text or title LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		@posts = Post.all.order("created_at DESC")
		render 'posts/userIndex'
	end
	def listUsers
		@users = User.all.order("id")
	end
	def listAllLogs
		if @logs = Activitylog.all.order("created_at DESC")
			render "listLogs"
		else
			render :json 
		end
	end
	def listLogs
		@logs = Activitylog.where(user_id: params[:id]).order("created_at DESC")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.record_activity("Created new account")
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	layout 'application'
    before_filter :set_constants

    def set_constants
    	if user_signed_in?
    		@lists = Post.where(user_id: current_user.id).order("created_at DESC")
    	end
    end

  	def record_activity(note)
	    @activity = Activitylog.new
	    if user_signed_in?
	   		@activity.user_id = current_user.id
	    else
	    	@activity.user_id = "guest"
	    end
	    @activity.note = note
	    @activity.browser = request.env['HTTP_USER_AGENT']
	    @activity.ip_address = request.env['REMOTE_ADDR']
	    @activity.controller = controller_name 
	    @activity.action = action_name 
	    @activity.params = params.inspect
	    # @activity.save
	end

  	protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.new 
		@comment.user_id = current_user.id 
		@comment.post_id = params[:post_id] 
		@comment.body = params[:comment][:body]
		@comment.save
		# @comment = @post.comments.create(params[:comment].permit(:body) )
		redirect_to post_path(@post)		
	end
	def destroy
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    if @comment.user_id == current_user.id || @comment.post.user == current_user || current_user.admin
		    @comment.destroy
		end
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
require 'json'

class PostsController < ApplicationController

	before_action :authenticate_user!, :only => [:new, :edit, :update, :create, :destroy]

	def new	
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])		
	end

	def update
	  	@post = Post.find(params[:id])
	  	if @post.user_id == current_user.id || current_user.admin
		  if @post.update(params[:post].permit(:title, :text))
		    redirect_to @post
		  else
		    render 'edit'
		  end
		else
			redirect_to user_index_path(current_user.id)
		end
	end

	def index
	end

	def userIndex
		if current_user.admin && params[:id].to_i == current_user.id.to_i	# redirect for admin to admins controller
			redirect_to admin_index_path
		elsif current_user.id.to_i == params[:id].to_i # seeing own feed
			@posts = Post.where("created_at > ?", Time.now - 1.month).order("created_at DESC").limit(10)
			record_activity("Visited own feed of user.id=" + params[:id].to_s)
		else											# seeing someone's profile/index
			@posts = Post.where(user_id: params[:id])
			record_activity("Visited profile of user.id=" + params[:id].to_s)
		end
	end

	def tags
		if params[:tag]
			@posts = Post.tagged_with(params[:tag])
			puts @posts
			render "userIndex"
		end
	end

	def tags_list	
	end

	def create
		@post = Post.new post_params
		@post.user_id = current_user.id
		if @post.save
			respond_to do |format|
				record_activity("Created new account")
				format.html { redirect_to post_path(@post), notice: 'Post was successfully created.' }
	        	format.json { render json: post_path(@post), status: :created, location: @post }	 
	        end
		else
			respond_to do |format|
				format.html { render action: "new" }
		        format.json { render json: user_index_path(current_user.id).errors, status: :unprocessable_entity }
		    end
		end
	end

	def show
		record_activity("Visited post.id=" + params[:id].to_s)
		@post = Post.find(params[:id])
	end

	def destroy
	  @post = Post.find(params[:id])
	  if @post.user_id == current_user.id || current_user.admin
	 	@post.destroy
	 	record_activity("Deleted post.id=" + params[:id].to_s)
	  end
	  redirect_to user_index_path(current_user.id)
	end

	def search
		@posts = Post.search(params[:search])
		render 'userIndex'
	end

	private

		def post_params
			params.require(:post).permit(:title, :text, :tag_list)
		end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%=l post.created_at %></td>
        <td><%= link_to post.user.username, user_index_path(post.user) %></td>
        <% if post.user_id == current_user.id || current_user.admin %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini btn-info' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/admins/listLogs.html.erb
<%- model_class = Activitylog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:log_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th> 
      <th><%= model_class.human_attribute_name(:event) %></th> 
      <th><%= model_class.human_attribute_name(:action) %></th> 
    </tr>
  </thead>
  <tbody>
	<% @logs.each do |log| %>
	<tr>
    <td><%= log.id %></td>
		<td><%= log.user_id %></td>
		<td><%= log.created_at %></td> 
    <td><%= log.note %></td>
    <td><%= log.action %></td>

	</tr>
	<% end %>
  </tbody>
  </table>

app/views/admins/listUsers.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th> 
    </tr>
  </thead>
  <tbody>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.id %></td>
		<td><%= link_to user.username, user_index_path(user.id) %></td>
		<td><%= user.email %></td>
		<td><%= user.created_at %></td>
    <td><%= link_to "Logs", admin_user_logs_path(user.id), :class => 'btn btn-mini btn-info' %></td>
	</tr>
	<% end %>
  </tbody>
  </table>

app/views/comments/_comment.html.erb
<p>
  <strong>By:</strong>
  <%=link_to comment.user.username, user_index_path(comment.user) %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
<% if user_signed_in? %>
	<% if current_user==comment.user  || current_user.admin %>
	  <%= link_to 'Delete Comment', [comment.post, comment],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	<% end %>
<% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href='/'>
        EnrichmentForum
        <sup style="font-size:14px; color: #999;">beta</sup>
        </a>
        <div class="nav-collapse">
          <ul class="nav">
          <% if user_signed_in? %>
            <li><%= link_to current_user.username, user_index_path(current_user.id) %></li>
            <% if current_user.admin %>
              <li><%= link_to "Users", admin_list_users_path %></li>
              <li><%= link_to "Logs", admin_list_logs_path %></li>
            <% end %>
          <% end %>
            <li><%= link_to "newPost", new_post_path%></li>
            <li><%= link_to "Tags", tags_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li>
              <%= form_tag search_path, :method => :get, :class => "navbar-search" do %>
             <p>
                  <%= text_field_tag :search, params[:search], :class => "search-query span2", :placeholder => "Search" %>
              </p>
              <% end %>
            </li>
            <li>
            <% if user_signed_in? %>
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path %>
            <% end %> 
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        We are a consortium of senior school teachers with over two decades of experience in 

leading Public Schools of Delhi. Alongside regular school teaching we have also been 

involved in teacher training and re-orientation work for over 15 years. Our workshops have 

benefited hundreds of teachers and received enthusiastically. 
      <% if user_signed_in? %>
        <h3>User History</h3>
        <ul>
        <% @lists.each do |list| %>
          <li><%= link_to list.title, post_path(list.id) %> | <%= list.created_at.strftime("%d %b. %Y") %></li>
      <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<!-- <script type="text/javascript" src="assets/javascripts/tinymice/js/tinymice/tinymice.min.js"></script> -->
<script>
        tinymce.init({selector:'textarea'});
</script>
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
<% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %>   
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tag_list ,"Tags (Seperate By commas)", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_index_path(current_user.id), :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<div align="center">
<a class="brand" href='/'>
   <%= image_tag "img.png" %>
</a>
</div>
<h3>Welcome To Enrichment Forum</h3>
We are a consortium of senior school teachers with over two decades of experience in 

leading Public Schools of Delhi. Alongside regular school teaching we have also been 

involved in teacher training and re-orientation work for over 15 years. Our workshops have 

benefited hundreds of teachers and received enthusiastically. 

   We have been repeatedly asked to give this effort a formal ground so that institutes and 

teachers can directly benefit from our experience. Towards this endeavour we are presenting 

a series of interactive workshops which can exclusively be designed as per the need of 

the school and the teachers. Our workshops are goal driven which is the outcome of our 

immense dedication and experience. We take this liberty to say
<p></p>

                       <div align="center"><strong> “WE KNOW TEACHERS LIKE NO OTHERS” </div></strong>
<p></p>

  A teacher can never afford to stop learning, as learning is synonymous with GROWTH. In 

the world of today, you can be either growing or you could be decaying, there is no middle 

ground. Often the schools are stuck with teachers that do not meet their standards and 

do not delivered the desired results. Like students, teachers also require some  instrument 

which guide them to get the desired result .We are that instrument which can bring the 

change in the teacher`s  outlook, personality, confidence and the skills. We can provide the 

very much needed platform to the teachers to enrich themselves from the experience of the 

others in the same field. This platform can be used by the teachers to discuss freely their 

requirements, area of difficulty, need of useful resources etc. etc the never ending list.

<p></p>         Our workshops are experiences in active learning. Our workshops are aimed at 

empowering the teachers to acquire the much needed knowledge booster and become 

a good leader, motivator and great mentor. When teachers work together, sit together, 

solve and share problems, they re-interpret ideas and concepts in unanticipated ways. This 

improves learning for teachers at several levels. 

<p></p>The important thing in this learning process is to remain involved with the children and to 

stop them from asking question the teacher must allow the child to dream and imagine. 

They must be receptive to new ideas and must be thorough in his/her subject. And the last, 

teacher must learn with time to enhance his knowledge as Knowledge is Power.

In our forthcoming series, we are presenting a workshop in Physics, Chemistry and 

Mathematics for practicing teachers. This workshop will review all basic concepts of classes 

XI and XII, with the intent of exploring the proper manner to present the above three 

subjects in the classroom. The special emphasis will be laid on:
<p></p>
<ul>
<li> Teaching of Difficult topics</li>

<li>Interesting ways of teaching those topics which majority of the students consider </li> 

<li>Integration of different topics within a given subject as well as integration of physics , 

chemistry and mathematics, in order to enhance understanding of the subject and 

save time too</li> 

<li>Clearing queries/ doubts of the practicing teachers </li> 
</ul> 

Significant efforts will be devoted on developing an understanding of the difficult

Concepts, how to formulate questions in order of increasing difficulty level, in order to 

ensure confidence of the teachers and maximize students success.

The workshop will be conducted (duration of workshop can be one day or two days) in a 

number of sessions:
<p></p>

Session 1 – Effective and interesting ways of teaching Physics, Chemistry, 
<p></p>
Session 2 – Intra and inter disciplinary way of teaching Physics ,Chemistry and
<p></p>
Session 3 – Interactive Doubt clearing session
<p></p>
Session 4- Activity based learning session
<p></p>
      We do not end our support to you here just by conducting and concluding the 

workshop but providing a helping hand to the teachers when and where they required. 

The teachers and the school can also be in touch with us electronically using email, mobile 

                   Mathematics

                   Mathematics
<p></p>
We would like to have an opportunity to meet you and present the programme and to enlist 

your support in conducting the workshop in your esteemed school. We are positive that 

teachers of your school will find this workshop beneficial and result -oriented. We would like 

to look forward to associating with your school.
<p></p>
       Thanks and Regards
<p></p>
EDUCATIONAL CONSULTANTS
<p></p>
enrichmentforum@gmail.com<p></p>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:tags)%>:</strong></dt>
  <dd><%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></dd>
  <dt><strong>By:</strong></dt>
  <dd><%= link_to @post.user.username, user_index_path(@post.user) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= raw @post.text %></dd>
</dl>

<div class="form-actions">
<% if user_signed_in? %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_index_path(current_user.id), :class => 'btn'  %>
  <% if current_user.id == @post.user_id || current_user.admin %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_post_path(@post), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
<% else %>
  <%= link_to t('.home', :default => t("helpers.links.home")),
              root_path, :class => 'btn'  %>
<% end %>
</div>

<h4>Comments</h4>

<%= render @post.comments %>

<h3>Add a comment:</h3>

<%= render "comments/form" %>

app/views/posts/tags_list.html.erb
<div id="tag_cloud" class="span9">
<table class="table table-striped">
  <thead>
  	<th>Tag Name</th>
  	<th>Related Posts</th>
  </thead>
  <tbody>
  <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
    <tr>
    	<td><%= link_to tag.name, tag_path(tag.name), class: css_class %></td>
    	<td><%= tag.count%></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/posts/userIndex.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%=l post.created_at %></td>
        <td><%= link_to post.user.username, user_index_path(post.user) %></td>
        <% if user_signed_in? %>
          <% if post.user_id == current_user.id || current_user.admin %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_post_path(post), :class => 'btn btn-mini btn-info' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        post_path(post),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>